apiVersion: v1
kind: Service
metadata:
  name: service-estate
spec:
  selector:
    app: service-estate
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 30002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-estate
spec:
  selector:
    matchLabels:
      app: service-estate
  replicas: 1
  template:
    metadata:
      labels:
        app: service-estate
    spec:
      containers:
        - name: server
          image: vitalyaboroda/service-estate
          ports:
            - name: http
              containerPort: 8082